# Đổi port nếu cổng 8080 trùng với app khác
server.port=8080

# Cấu hình SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=khoga_coffee_shop;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update

# Tắt cache Thymeleaf để code giao diện nhanh hơn
spring.thymeleaf.cache=false
