import { apiClient } from './client';
import type { ApiResponse, PageResponse, Role } from './types';

/** com.khoga.user.dto.UserResponse */
export interface User {
  id: string;
  employeeId: string;
  username: string;
  fullName: string;
  role: Role;
  email: string | null;
  phone: string | null;
  storeId: string | null;
  active: boolean;
}

export interface ActivityEntry {
  actionType: string;
  entityAffected: string;
  at: string;
}

/** com.khoga.user.dto.UserDetailResponse */
export interface UserDetail extends User {
  lastLoginAt: string | null;
  recentActivity: ActivityEntry[];
}

/** CreateUserRequest — username + temp password are generated by the backend and emailed. */
export interface CreateUserInput {
  fullName: string;
  role: Role;
  email: string;
  phone?: string;
  storeId?: string | null;
}

/** UpdateUserRequest — role/branch/contact only (status via activate/deactivate). */
export interface UpdateUserInput {
  role?: Role;
  storeId?: string | null;
  email?: string;
  phone?: string;
}

// Up to 100 staff in one page; search/role filtering done client-side (see UserList).
export async function listUsers(): Promise<User[]> {
  const res = await apiClient.get<ApiResponse<PageResponse<User>>>('/users', { params: { size: 100 } });
  return res.data.data.content;
}

export async function getUser(id: string): Promise<UserDetail> {
  const res = await apiClient.get<ApiResponse<UserDetail>>(`/users/${id}`);
  return res.data.data;
}

export async function createUser(input: CreateUserInput): Promise<User> {
  const res = await apiClient.post<ApiResponse<User>>('/users', input);
  return res.data.data;
}

export async function updateUser(id: string, input: UpdateUserInput): Promise<User> {
  const res = await apiClient.put<ApiResponse<User>>(`/users/${id}`, input);
  return res.data.data;
}

export async function setUserActive(id: string, active: boolean): Promise<User> {
  const res = await apiClient.post<ApiResponse<User>>(`/users/${id}/${active ? 'activate' : 'deactivate'}`);
  return res.data.data;
}
